#!/usr/bin/env python3

import sys
import os

if len(sys.argv) < 3:
    print("USAGE: gen-srctests TESTS... OUTPUT_DIR")
    exit(1)

files = {}
expected = {}

output = sys.argv[-1]

for srctest in sys.argv[1:len(sys.argv)-1]:
    file = os.path.splitext(os.path.basename(srctest))[0]
    files[file] = {}
    expected[file] = {}
    common = []
    common_expected = []
    current = None
    with open(srctest, "r") as test:
        for line in test.readlines():
            if line.startswith("#---"):
                parts = line.split()
                if len(parts) == 1:
                    current = None
                if len(parts) != 2:
                    print(f"Failed to parse clover source test file {srctest}: bad line {line}")
                    sys.exit(1)
                current = parts[1].strip()
                if current in files[file]:
                    print(f"Failed to parse clover source test file {srctest}: duplicate subtest {current}")
                    sys.exit(1)
                files[file][current] = []
                expected[file][current] = []
            else:
                if current is None:
                    common.append(line)
                    if line.find("#") != -1:
                        common_expected.append(line[line.find("#") + 1:].lstrip())
                else:
                    files[file][current].append(line)
                    if line.find("#") != -1:
                        expected[file][current].append(line[line.find("#") + 1:].lstrip())
        if len(files[file]) == 0:
            files[file] = ''.join(common)
            expected[file] = ''.join(common_expected)
        else:
            if len(common_expected) > 0:
                print(f"Failed to parse clover source test file {srctest}: found common expected output '{common_expected[0]}' but subtests exist")
                sys.exit(1)
            for k in files[file]:
                files[file][k] = ''.join(common + files[file][k])
                expected[file][k] = ''.join(expected[file][k])

cpptest = []

isdebug = 'debug' in output
cloverc = 'bin/debug/clover/clover' if isdebug else 'bin/release/clover/clover'
libpath = 'bin/debug/clover/test' if isdebug else 'bin/release/clover/test'
binarypath = 'bin/debug/clover/test/a.out' if isdebug else 'bin/release/clover/test/a.out'
prelude = f"""
#include "util/io.h"
#include "util/str.h"
#include "util/test/harness.h"
#include "spawn.h"
#include "fcntl.h"
#include "unistd.h"
#include "sys/wait.h"

namespace process {{
    extern i8* const* envp;
}}

i32 compile(const_slice<i8> src, const_slice<i8> outpath) {{
    vec<const_slice<i8>> argv;
    argv.push(cstring("-L{libpath}"));
    argv.push(cstring("-lsrctest"));
    argv.push(src);
    argv.push(cstring("-o"));
    argv.push(cstring("{binarypath}"));

    i32 result = process::exec(cstring("{cloverc}"), argv);
    if (result != 0)
        return result;

    const i8* outpath_cstr = tostring(outpath, i8(0)).data();
    fd nativeout = open(outpath_cstr, O_RDWR | O_CREAT | O_TRUNC, 0666);

    pid_t pid;
    posix_spawn_file_actions_t actions;
    posix_spawnattr_t attr;
    posix_spawn_file_actions_init(&actions);
    posix_spawn_file_actions_adddup2(&actions, nativeout, 1);
    posix_spawnattr_init(&attr);
    i8* ptr = nullptr;
    posix_spawn(&pid, "{binarypath}", &actions, &attr, &ptr, process::envp);
    waitpid(pid, &result, 0);
    delete[] outpath_cstr;
    close(nativeout);
    return result;
}}

const_slice<i8> read(const_slice<i8> path) {{
    auto info = file::pathinfo(path);
    slice<i8> str = {{ new i8[info.size], info.size }};
    auto f = file::openbuf(path, file::READ);
    assert(f != -1);
    file::readbuf(f, str);
    file::closebuf(f);
    while (str.last() == '\\n')
        str = str.take(str.size() - 1);
    return str;
}}

#define RUNTEST(src, expected) \\
    auto outpath = tostring(src, ".out"); \\
    i32 result = compile(src, outpath); \\
    if (result == 0) {{ \\
        auto out = read(outpath); \\
        auto exp = read(expected); \\
        ASSERT_EQUAL(out, exp); \\
        delete[] out.data(); \\
        delete[] exp.data(); \\
    }} else {{ \\
        auto msg = read(outpath); \\
        println(msg); \\
        delete[] msg.data(); \\
        process::exit(1); \\
    }}

"""

for file in files:
    if isinstance(files[file], str):
        path = os.path.join(output, file + ".cl")
        expected_path = os.path.join(output, file + ".expected")
        with open(path, "w") as out:
            out.write(files[file])
        with open(expected_path, "w") as out:
            out.write(expected[file])
        cpptest.append(f"TEST(source_{file}) {{ RUNTEST(cstring(\"{path}\"), cstring(\"{expected_path}\")); }}\n")
    else:
        for k in files[file]:
            name = file + '_' + k
            path = os.path.join(output, name + ".cl")
            expected_path = os.path.join(output, name + ".expected")
            with open(path, "w") as out:
                out.write(files[file][k])
            with open(expected_path, "w") as out:
                out.write(expected[file][k])
            cpptest.append(f"TEST(source_{name}) {{ RUNTEST(cstring(\"{path}\"), cstring(\"{expected_path}\")); }}\n")

with open(os.path.join(output, "clover-srctests.cpp"), "w") as out:
    out.write(prelude)
    out.write(''.join(cpptest))